{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
{{- $fullname := include "cap.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}-objectstore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cap.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}{{ toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cap.selectorLabels" (dict "root" . "component" "minio") | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- if and .Values.mysql.enabled .Values.metrics.mysqldExporter.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cap.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}{{ toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cap.selectorLabels" (dict "root" . "component" "mysql") | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
{{- end }}
